In [1]:
import h5py
import numpy as np
import torch

from torch.utils.data import ConcatDataset, DataLoader
from torch_geometric.data import DataListLoader

/g/g92/noh1/.local/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from IPython.display import clear_output
from IPython.core.display import HTML
HTML("<style>.container { width:98% !important; }</style>")

In [3]:
os.chdir("..")
print("Current working directory:", os.getcwd())

Current working directory: /g/g92/noh1/FASTv2


In [5]:
data_dir = "./data/pdbbind2016"
file_name = "refined.hdf"

In [6]:
file_path = os.path.join(data_dir, file_name)
f = h5py.File(file_path, 'r')

In [7]:
data_names = name = list(f)

In [8]:
idx = 0
name = data_names[idx]
print(f[name].attrs["affinity"])
f[name].keys()

6.4


<KeysViewHDF5 ['pybel']>

In [9]:
for k in f[name].keys():
    print(k)
    for info in f[name][k]:
        print(f[name][k][info])

pybel
<HDF5 group "/10gs/pybel/processed" (1 members)>


In [18]:
f[name]["pybel"]["processed"]["pdbbind"]["data"]

<HDF5 dataset "data": shape (440, 22), type "<f4">

In [23]:
f[name]["pybel"]["processed"]["pdbbind"].attrs["van_der_waals"].shape

(440,)

In [19]:
f[name]["pybel"]["processed"]["pdbbind"]["data"][:]

array([[ 5.261486 ,  4.0609403, -4.5755405, ...,  0.       ,  1.       ,
         0.       ],
       [ 5.183486 ,  3.2499404, -3.3305416, ...,  0.       ,  0.       ,
         0.       ],
       [ 6.2884855,  2.1869397, -3.2925415, ...,  0.       ,  0.       ,
         0.       ],
       ...,
       [ 3.6274862, 11.01894  , -3.5255413, ...,  1.       ,  1.       ,
         0.       ],
       [ 3.6814861,  8.42094  , -2.5995407, ...,  1.       ,  1.       ,
         0.       ],
       [ 7.5784864,  5.92794  , -7.7265415, ...,  1.       ,  1.       ,
         0.       ]], dtype=float32)

In [9]:
f[name]["spatial"]["coords"][:]

array([[-1.6278286, -0.3490429,  2.8687363],
       [-1.5928288, -0.8380432,  4.3387375],
       [-0.833828 , -2.1590433,  4.4177322],
       ...,
       [ 7.3611717,  8.054957 , -1.6722641],
       [ 8.4101715,  7.103957 , -1.1192665],
       [ 6.345173 ,  7.237956 , -2.490265 ]], dtype=float32)

In [10]:
f[name]["spatial"]["node_feats"][:]

array([[1.7, 0. , 1. , ..., 0. , 0. , 1. ],
       [1.7, 0. , 1. , ..., 0. , 0. , 1. ],
       [1.7, 0. , 1. , ..., 0. , 0. , 1. ],
       ...,
       [1.7, 0. , 1. , ..., 0. , 0. , 0. ],
       [1.7, 0. , 1. , ..., 0. , 0. , 0. ],
       [1.7, 0. , 1. , ..., 0. , 0. , 0. ]], dtype=float32)

In [11]:
f[name]["spatial"]["dists"][:]

array([[ 0.       ,  1.5495967,  2.5111606, ..., 13.116784 , 13.122989 ,
        12.241332 ],
       [ 1.5495967,  0.       ,  1.5255699, ..., 13.978259 , 13.889751 ,
        13.223801 ],
       [ 2.5111606,  1.5255699,  0.       , ..., 14.4420185, 14.209612 ,
        13.695331 ],
       ...,
       [13.116784 , 13.978259 , 14.4420185, ...,  0.       ,  1.5200685,
         1.5391134],
       [13.122989 , 13.889751 , 14.209612 , ...,  1.5200685,  0.       ,
         2.4822996],
       [12.241332 , 13.223801 , 13.695331 , ...,  1.5391134,  2.4822996,
         0.       ]], dtype=float32)

In [12]:
# f.close()

In [16]:
x = np.concatenate((f[name]["spatial"]["coords"][:], f[name]["spatial"]["node_feats"][:]), axis=-1)
x.shape

(513, 23)

In [17]:
x

array([[-1.6278286, -0.3490429,  2.8687363, ...,  0.       ,  0.       ,
         1.       ],
       [-1.5928288, -0.8380432,  4.3387375, ...,  0.       ,  0.       ,
         1.       ],
       [-0.833828 , -2.1590433,  4.4177322, ...,  0.       ,  0.       ,
         1.       ],
       ...,
       [ 7.3611717,  8.054957 , -1.6722641, ...,  0.       ,  0.       ,
         0.       ],
       [ 8.4101715,  7.103957 , -1.1192665, ...,  0.       ,  0.       ,
         0.       ],
       [ 6.345173 ,  7.237956 , -2.490265 , ...,  0.       ,  0.       ,
         0.       ]], dtype=float32)

In [18]:
f.close()