In [1]:
import numpy as np
from scipy.linalg import lu

In [2]:
def lu_factorization(matrix):
    """
    Computes the LU factorization of a square matrix using scipy.linalg.lu.

    Args:
        matrix (numpy.ndarray): A square matrix.

    Returns:
        tuple: A tuple containing the lower triangular matrix (L) and
               the upper triangular matrix (U).
    """
    P, L, U = lu(matrix)
    return L, U

In [3]:
# --- Examples ---

print("--- Examples of LU Factorization using scipy.linalg.lu ---")

# Example 1: 5x5 Matrix
print("\n--- Example 1: 5x5 Matrix ---")
matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print("Original Matrix:\n", matrix1)
L1, U1 = lu_factorization(matrix1)
print("L Matrix:\n", L1)
print("U Matrix:\n", U1)
print("Verification (L @ U):\n", np.round(L1 @ U1, 5))


--- Examples of LU Factorization using scipy.linalg.lu ---

--- Example 1: 5x5 Matrix ---
Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
L Matrix:
 [[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
U Matrix:
 [[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
Verification (L @ U):
 [[7. 8. 9.]
 [1. 2. 3.]
 [4. 5. 6.]]


In [4]:
import numpy as np

def create_banded_matrix(n, lower_bandwidth, upper_bandwidth):
    """
    Creates a banded matrix of size nxn.

    Args:
        n (int): The size of the matrix (number of rows and columns).
        lower_bandwidth (int): The number of non-zero diagonals below the main diagonal.
        upper_bandwidth (int): The number of non-zero diagonals above the main diagonal.

    Returns:
        numpy.ndarray: The banded matrix.
    """
    matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            if -lower_bandwidth <= (j - i) <= upper_bandwidth:
                # You can assign specific values based on your PDE problem here.
                # For a general example, let's assign values based on the diagonal.
                if i == j:
                    matrix[i, j] = 2.0  # Main diagonal
                elif j == i + 1:
                    matrix[i, j] = -1.0 # First upper diagonal
                elif i == j + 1:
                    matrix[i, j] = -1.0 # First lower diagonal
                elif j == i + 2 and upper_bandwidth >= 2:
                    matrix[i, j] = 0.5  # Second upper diagonal (example)
                elif i == j + 2 and lower_bandwidth >= 2:
                    matrix[i, j] = 0.5  # Second lower diagonal (example)
                # Add more conditions for other diagonals as needed for your PDE

    return matrix

# Example usage for a tridiagonal matrix (common in 1D PDEs)
n = 5
lower_bw = 1
upper_bw = 1
tridiagonal_matrix = create_banded_matrix(n, lower_bw, upper_bw)
print("Tridiagonal Matrix (n=5):")
print(tridiagonal_matrix)

print("\n---------------------\n")

# Example usage for a matrix with a wider band (might arise in 2D PDEs)
n = 20
lower_bw = 2
upper_bw = 2
wider_banded_matrix = create_banded_matrix(n, lower_bw, upper_bw)
print(f"Banded Matrix (n=7, lower_bandwidth={lower_bw}, upper_bandwidth={upper_bw}):")
print(wider_banded_matrix)

# Save Matrix
filename="matrix.csv"
np.savetxt(filename, wider_banded_matrix, delimiter=',')
print(f"Matrix successfully saved to '{filename}'")


Tridiagonal Matrix (n=5):
[[ 2. -1.  0.  0.  0.]
 [-1.  2. -1.  0.  0.]
 [ 0. -1.  2. -1.  0.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  0. -1.  2.]]

---------------------

Banded Matrix (n=7, lower_bandwidth=2, upper_bandwidth=2):
[[ 2.  -1.   0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0. ]
 [-1.   2.  -1.   0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0. ]
 [ 0.5 -1.   2.  -1.   0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.5 -1.   2.  -1.   0.5  0.   0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.5 -1.   2.  -1.   0.5  0.   0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.5 -1.   2.  -1.   0.5  0.   0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.5 -1.   2.  -1.   0.5  0.   0.   0.   0.   0.
   0.   0.   0.   0.   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.5 -1.   2.  -1.  

In [9]:
import numpy as np
import random

def generate_random_lower_triangular(n):
    """Generates a random lower triangular matrix of size nxn."""
    L = np.random.rand(n, n)
    return np.tril(L)

def generate_random_upper_triangular(n):
    """Generates a random upper triangular matrix of size nxn."""
    U = np.random.rand(n, n)
    return np.triu(U)

def generate_random_permutation_matrix(n):
    """Generates a random permutation matrix of size nxn."""
    identity = np.identity(n)
    permutations = np.random.permutation(n)
    P = identity[permutations]
    return P

def compute_A_from_PLU(P, L, U):
    """Computes A = P^T L U."""
    P_transpose = np.transpose(P)
    temp_matrix = np.dot(L, U)
    A = np.dot(P_transpose, temp_matrix)
    return A

if __name__ == '__main__':
    n = 4  # Example size of the matrices

    # Generate random L and U matrices
    L = generate_random_lower_triangular(n)
    print("Random Lower Triangular Matrix L:\n", L)

    U = generate_random_upper_triangular(n)
    print("\nRandom Upper Triangular Matrix U:\n", U)

    # Generate a random permutation matrix P
    P = generate_random_permutation_matrix(n)
    print("\nRandom Permutation Matrix P:\n", P)

    # Compute A = P^T L U
    A = compute_A_from_PLU(P, L, U)
    print("\nComputed Matrix A (P^T L U):\n", A)

Random Lower Triangular Matrix L:
 [[0.75818697 0.         0.         0.        ]
 [0.01205861 0.64027817 0.         0.        ]
 [0.37375617 0.47257734 0.29047348 0.        ]
 [0.74893839 0.02928995 0.78753936 0.72900511]]

Random Upper Triangular Matrix U:
 [[0.79921671 0.11267777 0.41721822 0.80974867]
 [0.         0.1379658  0.45088842 0.15181364]
 [0.         0.         0.88743671 0.14206666]
 [0.         0.         0.         0.5691756 ]]

Random Permutation Matrix P:
 [[0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]

Computed Matrix A (P^T L U):
 [[0.29871218 0.10731352 0.62679437 0.41565885]
 [0.6059557  0.08543082 0.31632942 0.61394089]
 [0.59856408 0.08842972 1.02456858 1.13771349]
 [0.00963744 0.08969523 0.29372508 0.1069674 ]]
